Fix build on FreeBSD (amd64 and aarch64)
etlegacy/etlegacy pull request #2463
Opened 2024-01-26 15:53 UTC by alonsobsd

2024-01-26 16:50 UTC, rafal1137 requested changes
@alonsobsd I see its more about case sensitivity here
Can you add additional entry for small one ?
```cmake
"${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "amd64")
```

2024-01-26 17:23 UTC, alonsobsd commented
> @alonsobsd I see its more about case sensitivity here Can you add additional entry for small one ?
> 
> ```cmake
> "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "amd64")
> ```

Done

2024-01-26 17:52 UTC, jackeri commented
Work on the platform detection is already on the way on the android branch.. Wait for it to merge (maybe later this weekend).

2024-02-02 23:44 UTC, jackeri commented on src/renderercommon/tr_font.c
> -		if (rc)
This seems a bit of strange change

2024-02-08 13:00 UTC, merged