game: Retain old 'BG_PlayerTouchesItem' for CTF flags
etlegacy/etlegacy pull request #2831
Opened 2024-09-30 01:29 UTC by Vorschreibung

The newly introduced 'BG_PlayerTouchesItem' is working fine and dandy for medi/ammo packs, however it also affected mission objectives (CTF flags) in existing maps and ways that messed with player expectations.

This commit readds the old 'BG_PlayerTouchesItem' logic in 'BG_PlayerTouchesItemOld' and uses it whenever we are to intersect with CTF flag entities.

Fixes https://github.com/etlegacy/etlegacy/issues/2827

2024-09-30 22:29 UTC, Aranud requested changes

2024-09-30 22:29 UTC, Aranud commented on src/game/bg_public.h
> +qboolean BG_PlayerTouchesItemOld(playerState_t *ps, entityState_t *item, int atTime);
Perhaps a more generic / specific name would be welcome. 
Such as BG_PlayerTouchesItemSquare/CylinderBBox

2024-09-30 22:29 UTC, Aranud commented on src/game/g_local.h
> +	long classnameHash;             ///< derived from classname
Could it be separate in another PR ?

2024-09-30 23:03 UTC, Aciz commented on src/game/bg_public.h
> +qboolean BG_PlayerTouchesItemOld(playerState_t *ps, entityState_t *item, int atTime);
I'd propose `BG_PlayerTouchesItem` & `BG_PlayerTouchesObjective`, since the other is used exclusively for objectives, and the other is for all other items

2024-10-01 00:34 UTC, Vorschreibung commented
Resolved all review input. Ready to re-review/merge.

2024-10-01 00:38 UTC, ensiform commented
Instead of classname matching you can compare item giType with IT_TEAM which is only true for PW_REDFLAG / PW_BLUEFLAG (objectives) aka the 2 team'd flags

2024-10-01 00:41 UTC, Vorschreibung commented
> Instead of classname matching you can compare item giType with IT_TEAM which is only true for PW_REDFLAG / PW_BLUEFLAG (objectives) aka the 2 team'd flags

that's on `gitem_t` tho - `hit` is `gentity_t`

2024-10-01 00:43 UTC, ensiform commented
See 

```c
gentity_s::item
```

Which is valid pointer if its an item.

2024-10-01 00:44 UTC, Vorschreibung commented
> See
> 
> ```c
> gentity_s::item
> ```
> 
> Which is valid pointer if its an item.

Thanks! Exactly what we needed.

2024-10-01 12:38 UTC, merged