game: Fixup jump-crouch- and swim-hitbox
etlegacy/etlegacy pull request #2834
Opened 2024-09-30 19:37 UTC by Vorschreibung

'ClientHitboxMaxZ' and 'CG_ClientHitboxMaxZ' both are used to determine the hitbox of a player server and client side respectively.

In the case of holding crouch while in the air jumping, 'CG_ClientHitboxMaxZ' erroneously set the hitbox height to shoulder level. This is corrected by checking for not being in the air when the crouch flag is set.

In the case of swimming, crouching while swimming would also set the hitbox height to shoulder level.

Instead of removing this, it is made the default - as the swimming hitbox was comically tall anyhow and it is not expected to have a huge impact towards gameplay.

2024-09-30 19:38 UTC, Vorschreibung commented
before
https://github.com/user-attachments/assets/c32dea68-f171-436c-8101-6ee81f82005d

after
https://github.com/user-attachments/assets/08b2d77c-0e32-4a19-a2e6-66f280e701b9

2024-10-01 12:52 UTC, Aranud requested changes

2024-10-01 12:52 UTC, Aranud commented on src/cgame/cg_predict.c
> +		|| (legsAnimHash == 109666 || legsAnimHash == 109540) // or is swimming
Magic numbers :( Sad :(

2024-10-01 12:52 UTC, Aranud commented on src/game/g_client.c
> +		|| (hitEnt->legsFrame.animation->nameHash == 109666 || hitEnt->legsFrame.animation->nameHash == 109540) // or is swimming
Magic numbers :( Sad :(

2024-10-02 01:23 UTC, Vorschreibung commented
De-magicalized, found a better way. 🫶
Ready to review again.

2024-10-03 07:36 UTC, merged