Add version info to development builds loading panel
etlegacy/etlegacy pull request #2998
Opened 2024-11-26 21:32 UTC by csmaxpower

When the `DEVELOPMENT BUILD` label was added in (#2969), `ETLEGACY_VERSION` was removed due to space constraints.  The version information is extremely useful to have so this commit aims to solve both the need for the development build label as well as having version information on the loading panel.

Positioning of the start of the print was adjusted to account for having two lines versus one, as well as text sizing adjustments to ensure two lines are still readable within the desired area.  Keeping the version on a separate line also ensures space for longer build strings should it be necessary over the current example below rendered by this commit:

![image](https://github.com/user-attachments/assets/607054a2-6e1c-4efc-b332-60760ab91404)

2024-11-26 23:15 UTC, Vorschreibung commented
@csmaxpower 

1. Upper-text sticks a lot towards the top border - can you possibly move it a tad down?
2. Distance between Upper-text and Lower-text seems a bit much - can you possibly reduce it?
3. Lower-text draws onto the border of the text box - can you possibly move it up?
4. Was it on purpose that you switched `DEVELOPMENT BUILD` & `legacy` ? - This makes it now inconsistent to the normal version display that's shown when you don't play on a development build, see second attachment.

![image](https://github.com/user-attachments/assets/83d74c27-2ca6-486f-90e7-62743ed9a8df)

### Release build
![image](https://github.com/user-attachments/assets/5073cdb6-3fbb-4b8f-a316-3f09eec32b77)

2024-11-26 23:18 UTC, Vorschreibung requested changes

2024-11-26 23:18 UTC, Vorschreibung commented on src/cgame/cg_loadpanel.c
> +		{
@csmaxpower trailing spaces - please make sure you have the https://editorconfig.org/ plugin for your Editor/IDE enabled and push again

2024-11-26 23:18 UTC, Vorschreibung commented on src/cgame/cg_loadpanel.c
> +			CG_Text_Paint_Centred_Ext(x, y, 0.20f, 0.20f, clr3, va("^8DEVELOPMENT BUILD ^1%s", MODNAME), 0, 0, 0, &cgs.media.bg_loadscreenfont1);
@csmaxpower Like mentioned in https://github.com/etlegacy/etlegacy/pull/2998#issuecomment-2502158246 - are you sure you want to swap the va string parts? - If so, shouldn't you also switch them for line 346?

2024-11-27 00:04 UTC, csmaxpower commented
> * Upper-text sticks a lot towards the top border - can you possibly move it a tad down?
> * Distance between Upper-text and Lower-text seems a bit much - can you possibly reduce it?
> * Lower-text draws onto the border of the text box - can you possibly move it up?
> * Was it on purpose that you switched `DEVELOPMENT BUILD` & `legacy` ? - This makes it now inconsistent to the normal version display that's shown when you don't play on a development build, see second attachment. - Similarly the ingame menu also states:

New commit with the above requested changes has been made, including the reverting back to original label text sequence of `MODNAME` & `DEVELOPMENT BUILD`, which was left by mistake when trying to fit it all on one line originally.  See commit notes for further details on adjustments.

2024-11-27 00:20 UTC, Vorschreibung commented
@csmaxpower LGTM, thanks for the patch!

2024-11-27 00:20 UTC, Vorschreibung approved these changes

2024-11-29 08:33 UTC, merged

2024-11-29 08:33 UTC, Aranud commented
Thank you !